#!/bin/bash

set -x

docker-compose down

set -e
docker pull ubuntu:rolling
docker-compose build
docker-compose up
docker commit binja_unlicensed binja_licensed
docker rm binja_unlicensed
docker image prune
